# Generated by Django 3.0.7 on 2020-07-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='company_name',
        ),
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default='', verbose_name='User message to us.'),
            preserve_default=False,
        ),
    ]
