# Generated by Django 3.0.7 on 2020-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20200720_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, help_text='User message to us.', null=True),
        ),
    ]
