# Generated by Django 3.0.7 on 2020-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_auto_20200720_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='submitted',
            field=models.BooleanField(default=False, help_text='Is Submitted?'),
        ),
    ]
